version: '3.7'

services:

  web:
    build: .
    ports:
     - "5001:80"
    depends_on:
     - "postgres"

  postgres:
    container_name: 'postgres'
    image: postgres
    ports:
      - "5432:5432"
    environment:
      # change this for a "real" app!
      POSTGRES_PASSWORD: mysecretpasswordgit
    volumes:
      - ./data:/var/lib/postgresql/data1
